# Generated by Django 3.0.6 on 2020-05-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='l_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='locker',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='hits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(),
        ),
    ]
