# Generated by Django 3.0.6 on 2020-06-03 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20200524_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec', models.CharField(max_length=20)),
                ('prof', models.CharField(max_length=20)),
                ('bk', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=20)),
                ('credit', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('major', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Book')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
