# Generated by Django 3.0.6 on 2020-06-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20200604_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='bk',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='lec',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='major',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='prof',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='serial',
            field=models.CharField(max_length=40),
        ),
    ]
