# Generated by Django 3.0.6 on 2020-06-04 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20200604_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='bookid',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='uid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uid_buyer',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='cid',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='uid',
            new_name='user',
        ),
    ]
