# Generated by Django 3.0.6 on 2020-06-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20200604_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='buyer',
            new_name='buyer_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='user',
            new_name='user_id',
        ),
    ]
