# Generated by Django 3.0.6 on 2020-06-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_auto_20200611_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_img',
            field=models.TextField(null=True),
        ),
    ]
