# Generated by Django 3.0.6 on 2020-06-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_auto_20200613_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_img',
        ),
    ]
