# Generated by Django 3.0.6 on 2020-06-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_remove_book_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_img',
            field=models.FileField(default='/media/calculus.jpg', upload_to=''),
        ),
    ]
