# Generated by Django 3.0.6 on 2020-06-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0017_remove_book_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_img',
            field=models.TextField(default='https://storage.cloud.google.com/backpack_bucket/img/calculus.jpg?authuser=2&folder&hl=ko&organizationId'),
        ),
    ]
