# Generated by Django 3.0.6 on 2020-06-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0019_remove_book_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_img',
            field=models.FileField(default='/home/sweteam4/backend/backpack-server/backpack/media/calculus.jpg', upload_to=''),
        ),
    ]
