# Generated by Django 3.0.6 on 2020-06-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0020_book_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.FileField(default='media/calculus.jpg', upload_to='media'),
        ),
    ]
