# Generated by Django 3.0.6 on 2020-06-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0027_remove_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_t',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='start_t',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='week',
            field=models.CharField(default='', max_length=20),
        ),
    ]
