# Generated by Django 3.0.6 on 2020-06-13 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0028_auto_20200613_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='end_t',
            new_name='first_time',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='start_t',
            new_name='second_time',
        ),
    ]
