# Generated by Django 3.0.6 on 2020-06-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0029_auto_20200613_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='second_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
