# Generated by Django 3.0.6 on 2020-06-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0031_post_locker_check'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('course_id', 'user_id')},
        ),
    ]
